# -*- coding: utf-8 -*-
"""21i-1763.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GQDLahndaY-sdcuREsEhgj6d00e4SHCG
"""

#Question 1
import pandas as pd
import numpy as np
filepath = (r'C:\Users\K\Downloads\TimeTable, FSC, Fall-2022.xlsx')
sheets = pd.read_excel(filepath,sheet_name= None)
print(sheets)
sheets_name = pd.concat(sheets.values(), ignore_indexes = True)
sheets_name
df = pd.concat(sheet[frame])

#Question 2
df = pd.read_excel(r'C:\Users\K\Downloads\TimeTable, FSC, Fall-2022.xlsx', sheet_name = "Monday")
df = df.drop([0,1,2], axis = 0)
df= df.dropna(axis = 1, how = 'all')
df = df.replace(np.nan,'', regex = True)

#Question 5
df = pd.read_excel(r'C:\Users\K\Downloads\TimeTable, FSC, Fall-2022.xlsx', sheet_name = "Tuesday")
df = df.drop([0,1,2], axis = 0)
df = df.dropna(axis = 1, how = 'all')
df = df.set_index(df.columns[0])
df = df.replace(np.nan, 'Available', regex = True)
sum = 0
for x in range(4, len(df.index)):
    temp = 0
    for y in range(0, len(df.columns)):
        if df.iloc[x,y] == 'Available':
            temp = temp + 1
        print(f"Row{x+1}:{temp}empty slots are")
        print(f"Total slots that are empty:{sum}")
        df

